import sprite from '../../img/sprite.svg';
import mobileImg from '../../img/about/about-mobile.png';
import mobileImg2x from '../../img/about/about-mobile@2x.png';
import tabletImg from '../../img/about/about-tablet.png';
import tabletImg2x from '../../img/about/about-tablet@2x.png';
import desktopImg from '../../img/about/about-desktop.png';
import desktopImg2x from '../../img/about/about-desktop@2x.png';
import {
  AboutContentBoxStyle,
  AboutDescriptionStyle,
  AboutImgBoxStyle,
  AboutTitleStyle,
} from './AboutTextContant.styled';

export interface IAboutTextContentProps {}

export default function AboutTextContent(props: IAboutTextContentProps) {
  return (
    <AboutContentBoxStyle>
      <AboutTitleStyle>
        a Story that started with{' '}
        <span className="second-color">one simple ape</span>
      </AboutTitleStyle>
      <AboutDescriptionStyle className="top-text">
        WHO GOT FED UP WITH BORING AND HYPOCRITIC COMMONPLACE THIS IS HOW THE
        IDEA OF ESCAPING AND DYNAMIC JOURNEY ON THE YACHT
      </AboutDescriptionStyle>

      <AboutDescriptionStyle className="bottom-text">
        <svg className="x-icon" width={24} height={24} fill="#fff">
          <use href={`${sprite}#icon-x`}></use>
        </svg>
        <span>
          EACH ARTWORK IN THE COLLECTION TELLS A STORY OF ONE JOURNEY. ARTS ARE
          RANDOMLY GENERATED BY USERS
        </span>
      </AboutDescriptionStyle>
      <AboutImgBoxStyle>
        <picture>
          <source
            srcSet={`${desktopImg} 1x, ${desktopImg2x} 2x`}
            media="(min-width: 1280px)"
          />
          <source
            srcSet={`${tabletImg} 1x, ${tabletImg2x} 2x`}
            media="(min-width: 768px)"
          />
          <img
            srcSet={`${mobileImg} 1x, ${mobileImg2x} 2x`}
            src={mobileImg}
            alt="Banner images"
          />
        </picture>
      </AboutImgBoxStyle>
    </AboutContentBoxStyle>
  );
}
